{
 "title": "MPC Dashboard",
 "time": { "from": "2022-10-10T13:05:07.553Z", "to": "2022-10-10T13:19:59.587Z" },
 "panels": [
  {
   "title": "Actual Momentary Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ts as time, agv_id, momentary_power_consumption from agv_data order by ts;"
    }
   ]
  },
  {
   "title": "Predicted Momentary Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ts as time, agv_id, predicted_momentary_power_consumption from agv_predicted_mpc order by ts;"
    }
   ]
  },
  {
   "title": "Difference in actual and predicted momentary power consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select agv_data.agv_id, agv_data.ts as time, momentary_power_consumption - predicted_momentary_power_consumption as diff\nfrom agv_data\njoin agv_predicted_mpc on date_trunc('second', agv_data.ts) = date_trunc('second', agv_predicted_mpc.ts)\nwhere predicted_momentary_power_consumption != 0 order by agv_data.ts;"
    }
   ]
  }
 ]
}